name: "To deploy Python app"
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    if: ${{ success() && contains(github.event.head_commit.message, 'release') }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
     - name: checkout repo
       uses: actions/checkout@v3

     - name: executing remote ssh commands using ssh key
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         script: |
           touch perm
           echo `whoami` > perm
           sudo su -
           export DEBIAN_FRONTEND=noninteractive
           git clone https://github.com/sharma04500/hello.git || exit 0
           cd hello
           git pull origin main
           pyinstaller --clean --onefile hello.py
           cd
           sudo cp -rf hello /var/www/html/hello
           cd /var/www/html/hello
           systemctl restart apache2

### This script uses an active AWS EC2 instance with pip and pyinstaller pre installed and apache2 preconfigured.
### This pipeline automatically runs upon a commit with message containing the keyword "release"

